version: "2"
run:
  timeout: 3m
  skip-dirs:
    - mocks
    - migrations

output:
  sort-results: true

linnters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign

issues:
  max-issues-per-linter: 20
  max-issues: 50